### ISSUE TITLE
Github 用法

### ISSUE THREAD

**Issue by deancn** [studygolang/miniprogram#11]
1. 自动关连issue和pr
https://airdb.wiki/dev/wiki/github/issue.html

2. Git 分支约束
Git 分支的约束和管理
https://airdb.wiki/dev/wiki/git_branch_manage.html

**Comment by deancn** [comment]
@iscolt @Ac-Kevin  commit 可以自动关连issue, 可以看一下。   issue的id在 issue 的标题边上。

**Comment by wenyio** [comment]
git commit -m "xxx, #11" 这样子嘛

**Comment by deancn** [comment]
> git commit -m "xxx, #11" 这样子嘛
是的。

**Comment by deancn** [comment]
@nonespace    https://airdb.wiki/dev/wiki/github/issue.html
看看这个

**Comment by Ac-Kevin** [comment]
@deancn  OK
