### ISSUE TITLE
Vue MVVM 技术分享

### ISSUE THREAD

**Issue by deancn** [studygolang/miniprogram#3]

**Comment by nonespace** [comment]
已阅

**Comment by deancn** [comment]
> 已阅

这个得你准备材料了。    统一放在https://docs.qq.com 的 ppt里吧。

**Comment by nonespace** [comment]
https://github.com/nonespace/MVVm

**Comment by deancn** [comment]
@nonespace  给几点建议：
1.  确定受众群体，最好是有一个引入的过程。 比如先讲讲数据绑定，之前技术的弊端是什么， 再延伸到双向绑定。
2.  关于mvvm的应用场景， 应该给一点实际的例子，提供一些使用场景。 目标是让听众可以结合自己遇见的问题，判断是否使用这一项技术。
3.  参考下面文章，再深入理解一下。https://www.liaoxuefeng.com/wiki/1022910821149312/1108898947791072
