### ISSUE TITLE
首页列表内容 显示，显示1-2个demo即可。

### ISSUE THREAD

**Issue by deancn** [studygolang/miniprogram#4]
（注意点：1. 实现后，要逐步设计为组件, 2. 不用做布局，只要有内容即可。）

**Comment by wenyio** [comment]
PTAL

**Comment by deancn** [comment]
git pull 拉一下代码。
git merge dev 将dev 分支合并到 自己的分支。


将 该功能放在  component/listContent.vue 文件中。

**Comment by wenyio** [comment]
OK

**Comment by deancn** [comment]
https://github.com/studygolang/miniprogram/actions/runs/52189297

![image](https://user-images.githubusercontent.com/1617384/76295842-49ea8200-62f0-11ea-920c-4af9a150a4d0.png)

**Comment by wenyio** [comment]
PTAL

**Comment by deancn** [comment]
微信开发工具上， 有一个上传的功能。 上传一下。
