### ISSUE TITLE
首页布局初步设计-第一个版本

### ISSUE THREAD

**Issue by deancn** [studygolang/miniprogram#7]

**Comment by deancn** [comment]
@nonespace  帮忙协助一下首页内容布局。

pre-action:
1. git pull 拉最新代码
2. git merge dev  将dev分支合并到自己的开发分支。


post-action:
开发后，请在微信开发工具，进行上传。

**Comment by nonespace** [comment]
收到

**Comment by deancn** [comment]
![image](https://user-images.githubusercontent.com/1617384/76424481-4552c600-63e3-11ea-960a-6b5c46d89ec8.png)
这个是在组件 ListContent  中实现的逻辑。 


记得在自己的分支开发， 一定要将dev分支合并到自己的开发分支。

**Comment by deancn** [comment]
Good job.
