### ISSUE TITLE
增加一个 tab, 名称为"文档"

### ISSUE THREAD

**Issue by deancn** [studygolang/miniprogram#8]
不需要布局， 只要列表显示相关数据即可。

**Comment by Ac-Kevin** [comment]
#9  提交pr

**Comment by deancn** [comment]
@Ac-Kevin  change the target branch to `dev`.

**Comment by deancn** [comment]
只要列表显示相关数据即可。   
-- 应该有4个数据， 页面现在是空白页面。


git pull 拉一下代码。
git merge dev  将dev 分支合并到 自己的分支。

**Comment by deancn** [comment]
内容页面可以左右拖动， 需要固定一下。  


稍微细腻一点，不要太粗糙。
